name: CI Build

on: push

jobs:
  build:
    runs-on: macos-14
    defaults:
      run:
        shell: arch -x86_64 zsh -e {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Toolchains
        id: cache-toolchains
        uses: actions/cache@v4
        with:
          key: cache-key-${{ hashFiles('configure.sh') }}
          restore-keys: |
            cache-key-${{ hashFiles('configure.sh') }}
          path: |
            ./toolchains
      - name: Setup x86 Development Environment
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install Development Environment
        run: | # wtf?
          /usr/local/bin/brew install ninja meson cmake || /usr/local/bin/brew link --overwrite python@3
      - name: Configuration
        if: ${{ steps.cache-toolchains.outputs.cache-hit != 'true' }}
        run: ./configure.sh
      - name: Save Cache
        id: cache-save
        if: ${{ steps.cache-toolchains.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          key: cache-key-${{ hashFiles('configure.sh') }}
          path: |
            ./toolchains
      - name: Build
        run: |
          meson setup --cross-file build-win64.txt --native-file build-osx.txt -Dlocal_native_llvm=true -Dbuild_airconv_for_windows=true build --buildtype debugoptimized
          meson compile -C build
      - name: Tar
        run: tar -zcf artifacts.tar.gz build/src
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts.tar.gz
      - name: Tar cache
        run: tar -zcf cache.tar.gz toolchains
      - name: Upload cache as artifact
        uses: actions/upload-artifact@v4
        with:
          name: toolchains-cache
          path: cache.tar.gz